//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DisplayAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   추천도서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BOOK {
            get {
                return ResourceManager.GetString("BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   축하 메시지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CELEBRATION {
            get {
                return ResourceManager.GetString("CELEBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영어회화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONVERSATION {
            get {
                return ResourceManager.GetString("CONVERSATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   급식메뉴과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FOOD_MENU {
            get {
                return ResourceManager.GetString("FOOD_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _16 {
            get {
                object obj = ResourceManager.GetObject("_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _24 {
            get {
                object obj = ResourceManager.GetObject("_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _256 {
            get {
                object obj = ResourceManager.GetObject("_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _32 {
            get {
                object obj = ResourceManager.GetObject("_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _48 {
            get {
                object obj = ResourceManager.GetObject("_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   직업정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JOB {
            get {
                return ResourceManager.GetString("JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   낮아요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MessageTempDown {
            get {
                return ResourceManager.GetString("MessageTempDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   높아요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MessageTempUp {
            get {
                return ResourceManager.GetString("MessageTempUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홍보영상과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PROMOTION_MOVIE {
            get {
                return ResourceManager.GetString("PROMOTION_MOVIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   안전정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SAFTY_INFO {
            get {
                return ResourceManager.GetString("SAFTY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스승의날 메시지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEACHERS_DAY {
            get {
                return ResourceManager.GetString("TEACHERS_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   날씨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WEATHER {
            get {
                return ResourceManager.GetString("WEATHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   환영 메시지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WELCOME_MESSAGE {
            get {
                return ResourceManager.GetString("WELCOME_MESSAGE", resourceCulture);
            }
        }
    }
}
