//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayAdmin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jireh\\DisplaySharedData\\JSON\\")]
        public string JSON_FILE_PATH {
            get {
                return ((string)(this["JSON_FILE_PATH"]));
            }
            set {
                this["JSON_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MANAGEMENT")]
        public string ENT_USER {
            get {
                return ((string)(this["ENT_USER"]));
            }
            set {
                this["ENT_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jireh\\DisplaySharedData\\IMAGE\\")]
        public string IMAGE_FILE_PATH {
            get {
                return ((string)(this["IMAGE_FILE_PATH"]));
            }
            set {
                this["IMAGE_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jireh\\DisplaySharedData\\MOVIE\\")]
        public string MOVIE_FILE_PATH {
            get {
                return ((string)(this["MOVIE_FILE_PATH"]));
            }
            set {
                this["MOVIE_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.1\\")]
        public string ROOT_FILE_PATH {
            get {
                return ((string)(this["ROOT_FILE_PATH"]));
            }
            set {
                this["ROOT_FILE_PATH"] = value;
            }
        }
    }
}
